OBJS = ex1_11 ex1_16 ex1_20
CC = g++
CFLAGS = -Wall -pedantic

all: $(OBJS)

ex1_11:ex1_11.cpp
	$(CC) -o ex1_11 ex1_11.cpp

ex1_16:ex1_16.cpp
	$(CC) -o ex1_16 ex1_16.cpp

ex1_20:ex1_20.cpp
	$(CC) -o ex1_20 ex1_20.cpp -std=c++11

clean:
	-rm $(OBJS)